Sat Oct 30 03:31:24 2021

Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/dislash/application_commands/slash_client.py", line 1282, in _on_slash_command
    await app_command.invoke(inter)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/dislash/application_commands/slash_core.py", line 216, in invoke
    raise err
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/dislash/application_commands/slash_core.py", line 212, in invoke
    await self._maybe_cog_call(self._cog, interaction, interaction.data)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/dislash/application_commands/slash_core.py", line 37, in _maybe_cog_call
    return await self(inter, **params)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/dislash/application_commands/core.py", line 72, in __call__
    return await self.func(*args, **kwargs)
  File "main.py", line 482, in list_all_problems
    guild_id = ctx.guild.id
AttributeError: 'NoneType' object has no attribute 'id'


