Wed Nov  3 16:29:18 2021

Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/dislash/application_commands/slash_client.py", line 1282, in _on_slash_command
    await app_command.invoke(inter)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/dislash/application_commands/slash_core.py", line 216, in invoke
    raise err
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/dislash/application_commands/slash_core.py", line 212, in invoke
    await self._maybe_cog_call(self._cog, interaction, interaction.data)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/dislash/application_commands/slash_core.py", line 37, in _maybe_cog_call
    return await self(inter, **params)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/dislash/application_commands/core.py", line 72, in __call__
    return await self.func(*args, **kwargs)
  File "main.py", line 271, in generate_new_problems
    if ctx.guild != None and ctx.guild.id not in main_cache.get_guilds():
  File "/home/runner/TheDiscordMathProblemBot/helpful_modules/problems_module.py", line 653, in get_guilds
    self.update_cache()
  File "/home/runner/TheDiscordMathProblemBot/helpful_modules/problems_module.py", line 497, in update_cache
    problem = MathProblem.from_dict(self._sql_dict[key], cache = copy(self))
  File "/home/runner/TheDiscordMathProblemBot/helpful_modules/problems_module.py", line 151, in from_dict
    guild_id = int(guild_id)
ValueError: invalid literal for int() with base 10: 'null'


